spring:
  datasource:
    url: jdbc:mysql://47.113.179.246:3306/spring_security?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 47.113.179.246
    password: 159267348
server:
  port: 80